# ラベルの定義
labels:
  - name: "WIP"
    description: "作業中"
    color: "d4c5f9"
  - name: "レビュー待ち"
    description: "レビュー待ち"
    color: "bfe5bf"
  - name: "レビュー修正待ち"
    description: "指摘事項を修正してください"
    color: "fef2c0"