name: Labeler
on:   
  issue_comment:
    types: [created]

jobs:
  label:
    if: (github.event.issue.pull_request != null) && (github.event.comment.body == '/review' || github.event.comment.body == '/reject')
    runs-on: ubuntu-latest

    steps:
    - name: add review label
      if: github.event.comment.body == '/review'
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X PUT -d '{"labels": ["Review"]}' -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}/labels

    - name: add reject label
      if: github.event.comment.body == '/reject'
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X PUT -d '{"labels": ["Reject"]}' -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}/labels
